pub static ERROR_CODE_DATA_NOT_FOUND: u16 = 500;
pub static ERROR_CODE_DATA_RETRIEVAL_FAILED: u16 = 501;
pub static ERROR_CODE_DATA_INSERTION_FAILED: u16 = 502;
pub static ERROR_CODE_DATA_DELETION_FAILED: u16 = 503;
pub static RESPONSE_CODE_DATA_RETRIEVAL_SUCCESS: u16 = 201;
pub static RESPONSE_CODE_DATA_INSERTION_SUCCESS: u16 = 202;
pub static RESPONSE_CODE_DATA_DELETION_SUCCESS: u16 = 203;
