pub static ERROR_CODE_DATA_NOT_FOUND: i32 = -1;
pub static ERROR_CODE_DATA_RETRIEVAL_FAILED: i32 = -2;
pub static ERROR_CODE_DATA_INSERTION_FAILED: i32 = -3;
pub static RESPONSE_CODE_DATA_RETRIEVAL_SUCCESS: i32 = 1;
pub static RESPONSE_CODE_DATA_INSERTION_SUCCESS: i32 = 2;